apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-probes
  name: busybox-probes
spec:
  containers:
  - image: k8s.gcr.io/busybox
    name: busybox-probes
    args: 
    - /bin/sh 
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 120
    readinessProbe:
      exec:
        command:
         - cat 
         - /tmp/healthy
      failureThreshold: 30
      periodSeconds: 10
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
