apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: health-probes-deployment
  name: health-probes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-probes-deployment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: health-probes-deployment
    spec:
      containers:
      - image: health-probes
        imagePullPolicy: IfNotPresent
        name: health-probes
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 2
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 5   
        resources: {}
status: {}
